# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        # Filter name
        label: codalia.journal::lang.articles.filter_category
        # Model Class name
        modelClass: Codalia\Journal\Models\Category
        # Model attribute to display for the name
        nameFrom: name
        # Apply query scope
        scope: FilterCategories

    published_date:
        # Filter name
        label: codalia.journal::lang.articles.filter_date
        # Filter type
        type: daterange
        # SQL Conditions
        conditions: created_at >= ':after' AND created_at <= ':before'

    status:
        label: codalia.journal::lang.articles.filter_status
        type: group
        conditions: status in (:filtered)
        options:
            published: codalia.journal::lang.status.published
            unpublished: codalia.journal::lang.status.unpublished
            archived: codalia.journal::lang.status.archived

    field_group:
        # Filter name
        label: codalia.journal::lang.articles.filter_field_group
        # Model Class name
        modelClass: Codalia\Journal\Models\Group
        # Model attribute to display for the name
        nameFrom: name
        # Apply query scope
        scope: FilterFieldGroups

