# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Extra Field

# Model Form Field configuration
form: $/codalia/journal/models/extrafield/fields.yaml

# Model Class name
modelClass: Codalia\Journal\Models\ExtraField

# Default redirect location
defaultRedirect: codalia/journal/extrafields

# Create page
create:
    title: Create Extra Field
    redirect: codalia/journal/extrafields/update/:id
    redirectClose: codalia/journal/extrafields

# Update page
update:
    title: Edit Extra Field
    redirect: codalia/journal/extrafields
    redirectClose: codalia/journal/extrafields

# Preview page
preview:
    title: Preview Extra Field
